repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: '\.(pdb|gro|top|sdf)$'
  - id: debug-statements
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.41.0
  hooks:
  - id: markdownlint
    exclude: .github
    args: ["--disable", "MD013", "MD033", "MD024", "MD046"]
